services:
  redusql:
    build:
      context: .
      dockerfile: Dockerfile
    image: redusql:latest
    
    # Mount volumes for input queries and output results
    volumes:
      # Mount the queries directory for input SQL files and test scripts
      - ./queries:/queries
      # Mount the output directory for reduced queries
      - ./output:/output
      # Mount the benchmarks if you have them
      - ./benchmarks:/benchmarks
    
    # Working directory inside the container
    working_dir: /queries
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - OUTPUT_DIR=/output
    
    # Ensure the container can write to mounted volumes
    user: root
